kind: Service
apiVersion: v1
metadata:
  name: {{ include "react-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP